spring.application.name=SmartRef
spring.profiles.active=local

# Server
server.port=8080

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false

#2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:file:./db/mydb
spring.datasource.username=sa
spring.datasource.password=

# S3
spring.cloud.aws.credentials.access-key=AKIAU6GDYHQZ5WXJREN4
spring.cloud.aws.credentials.secret-key=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
spring.cloud.aws.region.static=ap-northeast-2
spring.cloud.aws.s3.bucket=clipo-bucket-123123

#redis
spring.data.redis.host=redis-13896.c340.ap-northeast-2-1.ec2.cloud.redislabs.com
spring.data.redis.port=13896
spring.data.redis.password=qKNIVLvT4cIL7T1P9Iaq35BYPQydZ54A
spring.data.redis.repositories.enabled=false

#jwt
jwt.secret.key=qdFs4ega3s5h1reh5h1r5tyregfd21tidr5efesdfeklskfjeirjldskfn


springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.display-request-duration= true