-- label
INSERT INTO label (name) VALUES
                             ('egg'),
                             ('fish'),
                             ('seafood'),
                             ('meat'),
                             ('poultry'),
                             ('processed_meat'),
                             ('dairy'),
                             ('cheese'),
                             ('yogurt'),
                             ('vegetable'),
                             ('fruit'),
                             ('legume'),
                             ('nut'),
                             ('seed'),
                             ('grain'),
                             ('rice'),
                             ('noodle'),
                             ('bread'),
                             ('oil'),
                             ('sauce'),
                             ('spice'),
                             ('raw'),
                             ('cooked'),
                             ('fermented'),
                             ('snack'),
                             ('dessert'),
                             ('beverage'),
                             ('leftover'),
                             ('other'),
                             ('fermented_product') ON CONFLICT (name) DO NOTHING;


-- location
INSERT INTO location (location_id, location_name, location_color) VALUES
                                                                      (1, 'fridges', '#F2A7A7'),
                                                                      (2, 'freezers', '#F2B8A0'),
                                                                      (3, 'freshs', '#F2C6A0'),
                                                                      (4, 'doors', '#F2D5A0'),
                                                                      (5, 'doorl', '#F2E4A0'),
                                                                      (6, 'doorr', '#E6F2A0'),
                                                                      (7, 'top', '#D4F2A0'),
                                                                      (8, 'middle', '#C2F2A0'),
                                                                      (9, 'down', '#B0F2A0'),
                                                                      (10, 'fridgel', '#A0F2A7'),
                                                                      (11, 'fridger', '#A0F2B8'),
                                                                      (13, 'right', '#A0F2C9'),
                                                                      (14, 'left', '#A0F2DA'),
                                                                      (15, 'most_top', '#A0F2EB'),
                                                                      (16, 'center_top', '#A0E8F2'),
                                                                      (17, 'center_bottom', '#A0D6F2'),
                                                                      (18, 'most_bottom', '#A0C4F2'),
                                                                      (19, 'most_left', '#A0B2F2'),
                                                                      (20, 'center_left', '#A7A0F2'),
                                                                      (21, 'center_right', '#B8A0F2'),
                                                                      (22, 'most_right', '#C9A0F2'),
                                                                      (23, 'most_top_left', '#DAA0F2'),
                                                                      (24, 'most_top_right', '#EBA0F2'),
                                                                      (25, 'most_bottom_left', '#F2A0E4'),
                                                                      (26, 'most_bottom_right', '#F2A0D2'),
                                                                      (27, 'center_top_right', '#F2A0C0'),
                                                                      (28, 'center_bottom_right', '#F2A0AE'),
                                                                      (29, 'center_top_left', '#F2C2B8'),
                                                                      (30, 'center_bottom_left', '#F2D4C2') ON CONFLICT (location_id) DO NOTHING;